# Generated by Django 4.1 on 2023-12-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, 'MAN'), (2, 'WOMAN'), (3, 'KIDS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[(1, 'Footwear'), (2, 'Clothes'), (3, 'Accessories'), (4, 'Clearance')], max_length=50),
        ),
    ]
