# Generated by Django 4.1 on 2023-12-19 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superapp', '0002_alter_product_category_alter_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superapp.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'MAN'), (2, 'WOMAN'), (3, 'KIDS'), (4, 'OTHER')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.IntegerField(choices=[(1, 'Footwear'), (2, 'Clothes'), (3, 'Accessories'), (4, 'Clearance'), (5, 'Technology')]),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('items_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superapp.product')),
            ],
        ),
    ]
