# Generated by Django 4.1 on 2023-12-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0005_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='9633b37b', max_length=100),
        ),
    ]
