# Generated by Django 4.1 on 2023-12-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0006_alter_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='449a2f18', max_length=100),
        ),
    ]
