# Generated by Django 4.1 on 2023-12-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0007_alter_product_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='5ef1aea5', max_length=100),
        ),
    ]
