# Generated by Django 4.1 on 2023-12-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0008_rename_p_id_product_id_alter_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='1ba6a85a', max_length=100),
        ),
    ]
