# Generated by Django 4.1 on 2023-12-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0009_alter_product_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                            Praesent sit amet aliquam elit, sed ornare arcu. Nam gravida pellentesque\n                            posuere. Sed sed metus in metus ullamcorper pellentesque. Maecenas tincidunt\n                            mi aliquam urna consectetur vulputate. Nullam sed dolor justo. Morbi ultrices\n                            enim lorem, sit amet feugiat lacus finibus eu. Proin condimentum massa enim,\n                            vel tristique tortor vehicula at. Integer ornare eget elit pellentesque hendrerit.\n                            Fusce vel imperdiet felis. In elit tellus, ultrices sed augue sit amet, dapibus malesuada velit.\n                            Proin iaculis nisl faucibus sagittis aliquet. Donec vehicula vestibulum mauris vitae tempor.\n                            Aliquam tempus, dui ac semper varius, sem felis sollicitudin risus, quis gravida tortor leo eget\n                            tortor. Vestibulum mauris arcu, tristique quis ultrices id, ornare quis ipsum. Aliquam convallis\n                            eleifend rhoncus. Nulla et felis sit amet arcu laoreet rhoncus ac id eros. Nulla at enim eu lacus\n                            viverra viverra. Curabitur leo tellus, congue ut imperdiet quis, porta sed diam. Curabitur pretium\n                            convallis faucibus. Nunc nec sem quis orci convallis pretium id in tellus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='c91e4000', max_length=100),
        ),
    ]
