# Generated by Django 4.1 on 2023-12-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0010_product_avail_product_desc_alter_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='fa99a4a2', max_length=100),
        ),
    ]
