# Generated by Django 4.1 on 2023-12-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0011_alter_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='64a20611', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.IntegerField(choices=[(1, 'Footwear'), (2, 'Clothes'), (3, 'Accessories'), (4, 'Clearance'), (5, 'Technology'), (6, 'Sports')]),
        ),
    ]
