# Generated by Django 4.1 on 2023-12-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0012_alter_product_reference_alter_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='1c23acc3', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.IntegerField(choices=[(1, 'Footwear'), (2, 'Clothes'), (3, 'Accessories'), (4, 'Clearance'), (5, 'Technology'), (6, 'Sports'), (7, 'Toy')]),
        ),
    ]
