# Generated by Django 4.1 on 2023-12-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0014_alter_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='85584183', max_length=100),
        ),
    ]
