# Generated by Django 4.1 on 2023-12-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0015_alter_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='48b358a7', max_length=100),
        ),
    ]
