# Generated by Django 4.1 on 2023-12-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0017_alter_product_category_alter_product_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='7cd4c6e2', max_length=100),
        ),
    ]
