# Generated by Django 4.1 on 2023-12-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0018_contact_alter_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='c742f90b', max_length=100),
        ),
    ]
