# Generated by Django 4.1 on 2023-12-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0020_checkout_alter_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(default='a7ca2862', max_length=100),
        ),
    ]
