# Generated by Django 4.1 on 2024-01-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("superapp", "0022_rename_cashondelivery_checkout_cashondelivery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="desc",
            field=models.TextField(
                default="Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n                            Praesent sit amet aliquam elit, sed ornare arcu. Nam gravida pellentesque\n                            posuere. Sed sed metus in metus ullamcorper pellentesque. Maecenas tincidunt\n                            mi aliquam urna consectetur vulputate. Nullam sed dolor justo."
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="reference",
            field=models.CharField(default="618a027a", max_length=100),
        ),
    ]
