# Generated by Django 4.1 on 2024-01-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("superapp", "0024_login_singup_alter_product_reference"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
        migrations.DeleteModel(
            name="Singup",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="username",
        ),
        migrations.AlterField(
            model_name="product",
            name="reference",
            field=models.CharField(default="5f6719a5", max_length=100),
        ),
    ]
